.eslintrc.json, js/cpu6502.js, js/main2e.js, test/cpu.spec.js, test/cpu6502.spec.js
Non read/write cycles may need some tweaking, but definitely more accurate than before.
=> CPU cycle accuracy

LICENSE, js/cards/disk2.js, js/cards/smartport.js, js/formats/2mg.js, js/formats/d13.js, js/formats/do.js, js/formats/format_utils.js, js/formats/nib.js, js/formats/po.js, js/formats/woz.js, js/main2.js, js/main2e.js
=> Crude native woz support.

apple2js.html, apple2jse.html, js/main2.js, js/main2e.js, js/ui/apple2.js, js/ui/printer.js
Before, the printer "paper" would just keep accumulating changes. Now
the `printer-modal` dialog has a "clear" button that will the paper.
=> Add a "Clear" button to clear the printer paper

js/base64.ts, js/cpu6502.ts
Adds some better typing to `cpu6502.ts` and `base64_encode`.
=> Minor type improvements

js/ui/apple2.js
Allow a Ciderpress binary file to be loaded directly into memory. Holding shift starts execution at the beginning of the file.
=> Basic binary file support.

js/apple2.ts, js/apple2io.ts, js/base64.ts, js/canvas.ts, js/cards/cffa.js, js/cards/disk2.ts, js/cards/nsc.js, js/cards/parallel.js, js/cards/ramfactor.js, js/cards/smartport.js, js/cards/thunderclock.js, js/cards/videoterm.js, js/gl.ts, js/mmu.ts, js/ram.ts, js/roms/rom.ts, js/types.ts, js/ui/apple2.js, js/ui/drive_lights.js, js/ui/keyboard.js, js/videomodes.ts, test/js/base64.test.ts
=> Flesh out some state stuff

package-lock.json
Strange things are afoot at the Circle K
=> SHA-nanigans

js/main2.ts, js/main2e.ts
Trivial conversion at this point.
=> Typescript mains

.github/workflows/nodejs.yml, apple2js.html, apple2jse.html, js/gl.ts, js/ui/apple2.ts
Feature request - loading binary files at arbitrary addresses. A bit quick and dirty but refactoring the UI taking a while so this will fill in for now. And quick fix some bleeding issues in HGR. Better fix pending.
=> Allow address input

apple2js.html, apple2jse.html, css/apple2.css, js/prefs.ts, js/ui/apple2.ts, js/ui/options_modal.ts, js/ui/screen.ts
Make full page sticky, and update the API calls for full screen to the latest stuff. Provide hot key to bring up preferences in full page mode.
=> Full page improvements

js/gl.ts
=> Clear whole screen during refresh

js/components/Apple2.tsx, js/components/Mouse.tsx, js/main2e.ts, js/ui/mouse.ts
Implemented as a non-rendering component because seemed interesting.
=> Preact mouse support

js/apple2io.ts, js/components/Apple2.tsx, js/components/Mouse.tsx, js/components/Slinky.tsx, js/components/ThunderClock.tsx
=> Add slinky and clock

css/apple2.css, index.html, js/ui/mouse.ts
=> Add touch screen handling

css/apple2.css, js/components/Apple2.tsx, js/components/AudioControl.tsx, js/components/ControlButton.tsx, js/components/ControlStrip.tsx, js/components/PauseControl.tsx
Separate control logic out of control strip, fix reset to not take focus.
=> Refactor some controls

.eslintrc.json, js/apple2io.ts, js/applesoft/compiler.ts, js/base64.ts, js/canvas.ts, js/cards/disk2.ts, js/cards/smartport.ts, js/cards/videoterm.ts, js/formats/create_disk.ts, js/formats/format_utils.ts, js/gl.ts, js/intbasic/decompiler.ts, js/mmu.ts, js/roms/rom.ts, js/ui/apple2.ts, js/ui/joystick.ts, js/ui/keyboard.ts, js/ui/tape.ts, test/cpu.spec.ts, test/js/formats/d13.spec.ts, test/js/formats/do.spec.ts, test/js/formats/po.spec.ts, test/js/formats/util.ts, test/js/util.test.ts
Modernizing one lint rule at a time.
=> Enforce strict equality

css/apple2.css, jest.config.js, js/components/Apple2.tsx, js/components/DiskII.tsx, js/components/ErrorModal.tsx, js/components/FileChooser.tsx, js/components/FileModal.tsx, js/components/Modal.tsx, js/components/hooks/useHash.ts, js/components/util/files.ts, package-lock.json, package.json, test/components/ErrorModal.spec.tsx, test/components/Modal.spec.tsx, test/jest-setup.ts
Adds an error modal, and hook up exception handling. Makes modals a top level element. Fixes hash value checking since I used that for manual testing.
=> Preact error dialog

js/components/ControlButton.tsx, js/components/ControlStrip.tsx, js/components/Printer.tsx, js/components/css/App.module.css, js/components/css/ControlButton.module.css, js/components/css/Modal.module.css, js/components/css/Printer.module.css
=> Preact printer

js/components/Debugger.tsx, js/components/css/App.module.css, js/components/css/Debugger.module.css, js/components/util/files.ts, js/debugger.ts
Simple controls to load a binary file into memory, and optionally begin execution.
=> Add load binary file

apple2js.html, apple2jse.html, css/apple2.css, js/components/Apple2.tsx, js/components/Mouse.tsx, js/components/Printer.tsx, js/components/Screen.tsx, js/components/css/BlockDisk.module.css, js/components/css/CPUMeter.module.css, js/components/css/ControlStrip.module.css, js/components/css/DiskII.module.css, js/components/css/Header.module.css, js/components/debugger/Applesoft.tsx, js/components/debugger/CPU.tsx, js/ui/apple2.ts
Fixes https://github.com/whscullin/apple2js/issues/142. Allow copy/paste outside of the screen, and make UI elements un-selectable so "select all" works better.
=> Fix copy paste outside of screen

js/canvas.ts, js/components/debugger/FileViewer.tsx, js/components/debugger/css/FileViewer.module.css
Criteria is very loose at the moment, anything ~8192 bytes. Lower bound was selected using images from https://archive.org/details/lgmappleii.
=> Add hires preview

js/cards/disk2.ts, js/cards/smartport.ts, js/components/BlockDisk.tsx, js/components/BlockFileModal.tsx, js/components/DiskDragTarget.tsx, js/components/DiskII.tsx, js/components/DownloadModal.tsx, js/components/Drives.tsx, js/components/FileModal.tsx, js/components/debugger/Disks.tsx, js/components/util/files.ts, js/formats/types.ts, js/ui/apple2.ts, js/ui/drive_lights.ts, test/js/cards/disk2.spec.ts, workers/format.worker.ts
Includes:
* Renaming the various drive number parameters and fields to `driveNo`.
* Organizing the imports of `disk2.ts`.
=> Minor cleanup

js/cards/disk2.ts, js/cards/smartport.ts, js/components/BlockDisk.tsx, js/components/BlockFileModal.tsx, js/components/DiskDragTarget.tsx, js/components/DiskII.tsx, js/components/DownloadModal.tsx, js/components/Drives.tsx, js/components/FileModal.tsx, js/components/debugger/Disks.tsx, js/components/util/files.ts, js/formats/types.ts, js/ui/apple2.ts, js/ui/drive_lights.ts, test/js/cards/disk2.spec.ts, workers/format.worker.ts
Reverts whscullin/apple2js#162 - Attempt to fix commit chain.
=> Revert "Minor cleanup"

js/ui/apple2.ts
Fixes https://github.com/whscullin/apple2js/issues/172
=> Don't reload already loaded disk

apple2js.html, apple2jse.html
Move buttons in save dialog closer to their relevant headers. Clarification for https://github.com/whscullin/apple2js/issues/175
=> Rearrange save buttons

js/ui/joystick.ts
Fixes https://github.com/whscullin/apple2js/issues/179
=> Fix disable mouse joystick

js/ui/mouse.ts
Try and avoid race conditions with touch down and up without getting more complicated.
=> Shorter touch delay, delay on release

test/js/cards/disk2.spec.ts
Before, the garbage test had only about a 92% chance of success because it relied on random numbers not being equal.  This change just repeats the test 5 times and allows up to 1 failure.  This increases the chance of the test passing to a hair less that 99.8%.
=> Improve Disk II test reliability

js/cards/cffa.ts
Creating a ProDOS indirection here served no purpose since the CFFA only deals in blocks.
=> Remove ProDOS layer from CFFA

.idx/dev.nix
I haven't had the patience to make the shell experience under nix livable, but it's kind of amusing still.
=> Add idx support

index.html, js/components/css/Header.module.scss
Hide the header and prevent scroll bounce.
=> Better Preact standalone behavior

js/canvas.ts, js/components/ClipboardCopy.tsx, js/gl.ts, js/ui/apple2.ts, js/videomodes.ts, package-lock.json
When in graphics mode, copy screen image instead of screen text.
=> Copy graphics

js/apple2.ts, js/canvas.ts, js/components/debugger/FileViewer.tsx, js/gl.ts, js/mmu.ts, js/ram.ts, js/videomodes.ts, test/js/canvas.test.ts, test/js/gl.test.ts, test/js/mmu.test.ts
Working towards being able to hot swap graphics renderers.
=> Move RAM storage out of graphics classes.

js/components/css/Screen.module.scss
=> Make sure exit full screen is on top, pt 2

js/mmu.ts
Bulk copy initial memory state instead of looping.
=> Streamline bank updates

js/components/util/files.ts, js/ui/apple2.ts
HEAD can fail where GET can succeed, so fail back to standard fetch if HEAD fails.
=> Graceful fallback if HEAD fails
