- js/main2e.js
In some browsers, in particular Chrome OS, pressing F1 opens a help
screen. This can be suppressed by calling preventDefault() on the
event.
> Prevent launching help when F1 is pressed

- js/main2e.js
Modern browsers set the 'location' property on keyboard events when
the key is located in several places. The ALT key, for example, can be
either on the left or the right side of the keyboard.
This change uses the location to determine which Apple key to
activate, if it is available, and defaults to the old behavior if not.
> Match the location of the Alt key to the activated Apple key

- css/apple2.css
- js/main2e.js
Normally, F2 causes the browser to go full-screen, showing only the
Apple screen. However, in Chrome, the user can exit full-screen mode
by pressing ESC. Since ESC is used frequently on the Apple //e, this
limits the utility of full-screen mode.
To work around this problem, this change adds Shift-F2, which will
make the Apple fill the window without going full-screen. This allows
the user to go make the window full-screen in some other way, thus
enabling the use of the ESC key.
Note that the method used is almost entirely implemented in CSS, with
just a few lines of code to change the classes on some elements. This
may not be the best long-term way of implementing this feature.
> Allow Shift-F2 to maximize the Apple screen in the window

- package.json
After running `npm install`, npm warns of a severe security vulnerability: https://www.npmjs.com/advisories/1164.
This change to `package.json` ensures the version of handlebars that is installed (because of jest) is unaffected.
This can be removed once jest releases a newer version that requires an unaffected version of handlebars.
> Remediate NPM Advisory 1164

- js/apple2.js
Before, when using `requestAnimationFrame`, the emulator did not save
the id returned by the browser. This broke the invariant of `run`,
namely that on exit either `runAnimationFrame` or `runTimer` would be
set. This meant that sometimes when the emulator restarted, there
would be two callbacks to `requetsAnimationFrame` run on every frame.
Now the id is saved correctly and the invariant of `run` is maintained.
> Fix a problem where sometimes the emulator would run too fast

- js/ui/apple2.js
Micromodal maintains a reference to the current open dialog in
this.modal. If one dialog is open while opening another, Micromodal
can get confused and maintain a reference to the wrong one.
One of the problems is that the close action is not instantaneous, so
even closing one dialog and opening another immediately after can
cause the problem.
This change adds a small delay before opening the alert dialog to work
around the problem.
> Fix bug where the alert dialog would not close

- apple2js.html
- apple2jse.html
- js/ui/apple2.js
- js/ui/printer.js
This change adds a download link to the printer dialog. The contents
of the download will be the raw bytes written to the parallel
interface. Note that often these bytes will have the high-bit set
causing the contents to look like gibberish.
However, this is extremely handy because it allows one to turn the
printer output into a PDF:
1.  In Appleworks (for example) configure an Apple ImageWriter in slot
1 and print a file.
2.  Download the printer output.
3.  Download the header file from https://github.com/AppleWin/AppleWin/files/1168047/ImageWriterEmulator-NoLF.ps.txt
4.  In Linux, run:
```shell
$ cat ImageWriterEmulator-NoLF.ps.txt raw_printer_output.bin | ps2pdf - printer_output.pdf
```
Note that the parallel port emulation in apple2js does not yet support
Print Shop, so I haven't …
> Track raw parallel port output and allow it to be downloaded

- jest.config.js
- package-lock.json
- package.json
- tsconfig.json
- webpack.config.js
This change adds basic, non-optimal support for Typescript with
webpack. It functions well in development mode and deployment boots
ProDOS. There are probably many ways this configuration can be sped
up, but I haven't investigated that yet.
Note that no Typescript files are added in this change; it is merely a
configuration change.
> Add configuration and dependencies to support Typescript

- js/base64.ts
- js/cpu6502.ts
- js/ram.ts
- js/symbols.js
- js/types.ts
- js/util.ts
- test/js/util.test.ts
This change converts `js/utils.js`, `js/base64.js`, `js/ram.js`, and `js/cpu6502.js`  to Typescript. It also adds tests for `js/util.js`. It does not attempt to convert `js/ram.js` into a proper class; that will be for a later refactoring.
The Typescript version of `js/cpu6502` is about 25% faster that the JavaScript version. The performance tests used are in https://github.com/iflan/apple2js/tree/perftests.
> Typescript conversion of several files, including js/cpu6502

- js/apple2io.js
- js/cards/smartport.js
- js/cpu6502.ts
- js/mmu.js
- js/ui/apple2.js
Apparently, I broke everything when I removed the underscores from the
field names and added them to the method names. The fix is just to
rename the methods `getCycles` and `getSync` and call it a day.
> Fix calls to cpu.cycles() and cpu.sync()

- js/cards/disk2.ts
During the typescriptification of `disk2.js`
(9d0ec5489c002834d71c68e0745ace3ae1d5336f), `drive`, a parameter
reference, was changed into `this.drive`, the current active disk, by
mistake. This change fixes that error.
> Fix issue #64

- js/gl.ts
- package.json
- types/apple2shader.d.ts
This adds a configuration that is equivalent to a Monitor II monitor
(at least according to the Open Emulator Project) to GL renderer.
This does not need a restart to take effect.
> Add green screen support for the GL renderer

- webpack.config.js
Before, the configuration used an array of regex literals. With
webpack 2.1.1, this breaks as it expects a list of glob strings.
See https://webpack.js.org/configuration/watch/#watchoptionsignored
> Fix webpack ignored files

- js/entry2.js
- js/entry2e.js
- package.json
- webpack.config.js
When using the old webpack-dev-server with webpack 5+, we get bitten
by webpack/webpack-dev-server#2692. This upgrades to 4.0.0-beta1 which
also (unhelpfully) changes the config options.  The `watchContentBase`
and `watchOptions` don't seem to have analogs in the new versions, but
I left them commented out for future reference.
Also, this does not update `package-lock.json` because even just
updating locally gave different output since I'm on a different
version of node, I'm guessing.
> Update webpack-dev-server to 4.0.0-beta1

- js/ui/apple2.ts
- js/ui/audio.ts
- js/ui/audio_worker.ts
- webpack.config.js
Two big issues were that TypeScript does not include the appropriate types, and figuring out what Webpack incantation to not have it fill the worker with framework that doesn't work in an AudioWorkletGlobalContext, which has no `this` or `self`. Other than that, actually using it is pretty simple.
> Use AudioWorklet where available

- js/cards/disk2.ts
- js/formats/create_disk.ts
- js/formats/d13.ts
- js/formats/do.ts
- js/formats/nib.ts
- js/formats/po.ts
- js/formats/types.ts
- js/formats/woz.ts
- js/ui/apple2.ts
- js/ui/drive_lights.ts
- json/disks/index.js
- test/js/formats/create_disk.spec.ts
- test/js/formats/testdata/json.ts
- test/js/formats/testdata/woz.ts
- test/js/formats/woz.spec.ts
Disk side information was being dropped and thus not displayable in the UI. This plumbs the value through various formats and adds some light testing.
Also fixes an issue where URL encoded hashes were not properly interpreted.
> Keep track of disk sides

- js/apple2.ts
- js/cpu6502.ts
- test/cpu-tom-harte.spec.ts
- test/cpu.spec.ts
- test/cpu6502.spec.ts
Implement all the NMOS 6502 "illegal" opcodes, and clean up some of the 65c02 behaviors. Add Rockwell 65c02 because that's more common in Apple //es. Illegal opcode names were taken from [here](http://www.ffd2.com/fridge/docs/6502-NMOS.extra.opcodes) but may be open to adjustment if something is more canonical.
Everything passes a sampling of the [Tom Harte](https://github.com/TomHarte/ProcessorTests). Larger samples overwhelm jest.
TODO: Random Sampling
WAI, HLT and STP instructions aren't respected at the moment except for setting flags. I'm undecided whether an additional flag check per operation by default is worth it for my purposes. The caller could handle the flags if it wished.
> No Opcode left behind

- js/components/FileChooser.tsx
- js/components/FileModal.tsx
- test/components/FileChooser.spec.tsx
This removes the `FileSystemFileHandleLike` interface in preference to
just implementing the correct interface. The advantage of the
`FileSystemFileHandle` interface is that it can be passed to the
worker directly to load the file.
> Implement `FileSystemFileHandle` for file input

- js/formats/2mg.ts
- js/util.ts
- test/js/formats/2mg.spec.ts
- test/js/formats/testdata/16sector.spec.ts
- test/js/formats/testdata/16sector.ts
Before, the offset for `FLAGS` in `2mg.ts` was `0x0A`, which is
incorrect according to the spec at:
https://apple2.org.za/gswv/a2zine/Docs/DiskImage_2MG_Info.txt
Now, all of the fields in the 2mg header are described, including
their lengths and any constraints.  These constraints are enforced by
`read2MGHeader` and tested by new tests.
> Fix 2mg header parsing and add tests

- js/components/Apple2.tsx
- js/components/util/promises.ts
This change adds `spawn` which takes a no-argument, promise-returning
function, calls it, and returns `void`.  This makes it easy to call
async blocks from `useEffect` and other places that don't take async
functions, but also makes such calls explicit.
> Add `spawn` as a way of calling promise-returning blocks

- js/components/Apple2.tsx
- js/components/util/promises.ts
- test/components/util/promises.spec.ts
Adds a `spawn` function to run asynchronous tasks. The task
function passed to `spawn` can take an `Interrupted` argument,
which is merely a method that returns `true` if the task should
stop doing work. Likewise, `spawn` returns an `Interrupt`
function that causes the `Interrupted` function to return `true`.
One use of `spawn` is to run asynchronous tasks from
`useEffect` blocks. The returned `Interrupt` functions can
serve as the `useEffect` cleanup function or be called from
the cleanup function.
Note that there's nothing magical about `Interrupt`—the
task must check `Interrupted` after every `await` to see
if it has been interrupted.
> Interruptable spawn

- js/cards/disk2.ts
- test/js/cards/disk2.spec.ts
This change adds basic read and write tests for nibble-based disks
for the Disk II card and fixes a few minor errors.
These tests are in preparation for refactoring.
> Add tests for the Disk II card

- js/applesoft/decompiler.ts
- js/cards/cffa.ts
- js/cards/disk2.ts
- js/cards/smartport.ts
- js/components/Apple2.tsx
- js/components/css/Tabs.module.css
- js/components/debugger/Debugger.tsx
- js/components/debugger/Disks.tsx
- js/components/debugger/FileViewer.tsx
- js/components/debugger/css/Disks.module.css
- js/components/debugger/css/FileViewer.module.css
- js/formats/dos/dos33.ts
- js/formats/format_utils.ts
- js/formats/po.ts
- js/formats/prodos/base_file.ts
- js/formats/prodos/bit_map.ts
- js/formats/prodos/constants.ts
- js/formats/prodos/directory.ts
- js/formats/prodos/file_entry.ts
- js/formats/prodos/sapling_file.ts
- js/formats/prodos/seedling_file.ts
- js/formats/prodos/tree_file.ts
- js/formats/prodos/utils.ts
- js/formats/types.ts
- js/intbasic/decompiler.ts
- test/js/applesoft/decompiler.spec.ts
This is a checkpoint for what turned out to be a lot of work to get a debugger tab with disk info. This shook out a ton of issues, particularly with the never before used ProDOS classes, but also widely across all disk code. 
There's still a ton of work to do, including unifying the interface for DOS 3.3 and ProDOS disks; supporting other disk formats; supporting more file formats for ProDOS; further cleaning up the ProDOS classes; cleaning up integer BASIC listings; supporting writing to disks; and reflecting internal disk state, like current block or track and sector. Oh, and write some tests.
> Debugger disk info groundwork

- js/components/Keyboard.tsx
Before, if the browser window wasn't tall enough to show the whole
keyboard, using the arrow keys in the window would cause the page
to move as well.  Now all key events that are sent to the keyboard
have `preventDefault()` called on them.
> Prevent the default action when the Apple keyboard handles a key

- js/cards/disk2.ts
- js/ui/audio.ts
Before, if there was an error in the audio worker or in the disk
worker, the emulator would not start. This could happen, for example,
if the page is loaded directly from disk in Chrome instead of through
a server.
Now, even if there is an error, the emulator will start.
> Make errors in the disk and audio workers not block the emulator

- js/cards/disk2.ts
- test/js/cards/disk2.spec.ts
Before, the `drives` field was an `array[0..1]` of `Drive`, but all of
the methods took a `DriveNumber`, which was `[1..2]`.  This meant that
code everywhere was always subtracting 1 from the drive number.
Now, `drives` is a `Record<DriveNumber, Drive>`, which means tha it
has indexes `1, 2` and there's no need to subtract 1 everywhere.
This change updates the `DiskII` class and its tests.
The motivation for this change is to slowly split the WOZ disk
implementation from the nibble disk implementation.  I've tried twice,
but the change has always grown too big and hairy, so I'm starting
very small this time and working my way up.
> Make `DiskII.drives` a `Record` instead of an array

- js/cards/cffa.ts
- js/cards/disk2.ts
- js/cards/smartport.ts
- js/components/DiskDragTarget.tsx
- js/components/DiskII.tsx
- js/components/FileModal.tsx
- js/components/debugger/Disks.tsx
- js/components/util/files.ts
- js/formats/block.ts
- js/formats/create_disk.ts
- js/formats/format_utils.ts
- js/formats/types.ts
- js/formats/woz.ts
- js/ui/apple2.ts
- test/js/cards/disk2.spec.ts
- test/js/formats/2mg.spec.ts
- test/js/formats/woz.spec.ts
Before, disk data was mixed in with state about the drive itself (like
track, motor phase, etc.). This made it hard to know exactly what data
was necessary for different image formats.
Now, the disk data is in a `disks` record in the `DiskII` object.  This
makes responsibility a bit easier to see.
This change is probably best reviewed one commit at a time since
they are small and targeted.
> Split disk data out into its own record

- js/cards/disk2.ts
- js/formats/dos/dos33.ts
- js/formats/format_utils.ts
- test/js/formats/format_utils.spec.ts
Before, `getBinary` did not work for 13 sector disks because it assumed that all tracks had 16 sectors. On top of that, `readSector` could not decode sectors with 5 and 3 encoding. And finally, `findSector` couldn't even find sectors with DOS 3.2 address fields.
All of these have been fixed and some tests added to make sure that they keep working.
> Add 13 sector disk support to `getBinary`

- js/cards/disk2.ts
- test/js/cards/disk2.spec.ts
Before, the `DiskII` object took care of both nibble disks and WOZ disks at the same time. This made it hard to see which code affected which disks.
Now, nibble disks are handled by the `NibbleDiskDriver` and WOZ disks are handled by the `WozDiskDriver`. This separation of code should lead to easeir testing and, perhaps, faster evolution of disk handling.
An upcoming change will move the `NibbleDiskDriver` and the `WozDiskDriver` to separate files.
This passes all tests, compiles, and runs both nibble disks and WOZ disks.
> Split handling of nibble disks and WOZ disks into separate drivers

- js/cards/disk2.ts
- js/cards/drivers/BaseDiskDriver.ts
- js/cards/drivers/EmptyDriver.ts
- js/cards/drivers/NibbleDiskDriver.ts
- js/cards/drivers/WozDiskDriver.ts
- js/cards/drivers/types.ts
- js/cards/smartport.ts
- js/components/BlockDisk.tsx
- js/components/BlockFileModal.tsx
- js/components/DiskDragTarget.tsx
- js/components/DiskII.tsx
- js/components/DownloadModal.tsx
- js/components/Drives.tsx
- js/components/FileModal.tsx
- js/components/debugger/Disks.tsx
- js/components/util/files.ts
- js/formats/types.ts
- js/ui/apple2.ts
- js/ui/drive_lights.ts
- test/js/cards/disk2.spec.ts
- workers/format.worker.ts
Before, all of the disk drivers were in the `disk2.ts` file. With this
change, they are now in separate files with a common `types.ts` file
for shared types. Now, none of the drives depend on the `disk2.ts`
except the WOZ driver that needs access to the sequencer rom. (This
may be moved in a future refactoring.)
> Split drivers into files

- js/formats/types.ts
- test/js/formats/types.spec.ts
Use array inclusion instead of object key check. Fixes issue identified in https://github.com/whscullin/apple2js/issues/175.
> Fix disk format type checks

- js/cpu6502.ts
Typescript was never quite happy with how it was being done before, this seems slightly more performant anyway.
> Simplify op table

- js/components/FileChooser.tsx
- test/components/FileChooser.spec.tsx
Before, the `FileChooser` could create a malformed `accept` parameter by repeating extensions if they were specified by several MIME types. This no longer happens and there is a test for it.
> Improve FileChooser behavior with file input element

- js/components/Slinky.tsx
- js/main2.ts
- js/main2e.ts
> Up RAMFactor memory to 8M

- apple2jse.html
Reset getting focus was preventing pasting from working, and since no other keys are focusable, was sort of confusing.
> Prevent reset getting focus

- apple2js.html
- apple2jse.html
- css/apple2.css
- js/components/ClipboardCopy.tsx
- js/components/ClipboardPaste.tsx
- js/components/ControlStrip.tsx
- js/ui/apple2.ts
Technically browser copy and paste controls work, but this is hard to discover and sometimes inaccessible. Attempts to address issues like https://github.com/whscullin/apple2js/issues/239. 
Future work would be to allow copying the graphics screen. Not sure how hard that would be.
> Add copy and paste control strip buttons
